// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJE0zt0yPYn7PK6lBCe1HC0QvPZfJLxzQ',
    appId: '1:95834653175:web:9e82f1e366663f7113eef2',
    messagingSenderId: '95834653175',
    projectId: 'mauritius-travel-guide-161dd',
    authDomain: 'mauritius-travel-guide-161dd.firebaseapp.com',
    storageBucket: 'mauritius-travel-guide-161dd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCCATDd__uvOmzJaGy9qOs4nbuduDCTOs',
    appId: '1:95834653175:android:ec35c8e115caabc413eef2',
    messagingSenderId: '95834653175',
    projectId: 'mauritius-travel-guide-161dd',
    storageBucket: 'mauritius-travel-guide-161dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIkurAcFMGKS5REs7VLi7sc8zidqxHLVE',
    appId: '1:95834653175:ios:dcfeeedd11f71e0f13eef2',
    messagingSenderId: '95834653175',
    projectId: 'mauritius-travel-guide-161dd',
    storageBucket: 'mauritius-travel-guide-161dd.appspot.com',
    iosClientId: '95834653175-6cmvv34viteuju6rds5pi9bshij2qp6b.apps.googleusercontent.com',
    iosBundleId: 'com.example.mauritiusTravelGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIkurAcFMGKS5REs7VLi7sc8zidqxHLVE',
    appId: '1:95834653175:ios:dcfeeedd11f71e0f13eef2',
    messagingSenderId: '95834653175',
    projectId: 'mauritius-travel-guide-161dd',
    storageBucket: 'mauritius-travel-guide-161dd.appspot.com',
    iosClientId: '95834653175-6cmvv34viteuju6rds5pi9bshij2qp6b.apps.googleusercontent.com',
    iosBundleId: 'com.example.mauritiusTravelGuide',
  );
}
